### ISSUE TITLE
How to use this program?

### ISSUE THREAD

**Issue by hhhhh322** [terrysimons/spine-python#5]
I move the build folders to the site-packages folder,but when I run the spine_pygame.py,It has some errors like this:

Python 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
= RESTART: C:\Users\30752\Downloads\spine-python-master\pyguts\examples\spine_pygame.py
pygame 2.1.2 (SDL 2.0.18, Python 3.7.8)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "C:\Users\30752\Downloads\spine-python-master\pyguts\examples\spine_pygame.py", line 7, in <module>
    import pyguts as spine
  File "C:\Users\30752\AppData\Local\Programs\Python\Python37\lib\site-packages\pyguts-1.0b14-py3.7.egg\pyguts\__init__.py", line 1, in <module>
    from Atlas import *
ModuleNotFoundError: No module named 'Atlas'

**Comment by ETO-QSH** [comment]
I am also troubled by this problem. Have you solved it or found any alternative in Python? In fact, I plan to play the animation in PyQt or PySide

**Comment by reisenmiao** [comment]
It seems there's something wrong with the arrangement of the files.

After modifying the project structure and fixing some unbelievably small bugs, it can actually run.
But turning it into a proper function package will need more work.

**Comment by ETO-QSH** [comment]
@reisenmiao I noticed that someone in the "Pull requests" mentioned how to do it, I didn't find all of them before and I'm not sure if it helped. May I ask, after more than ten years of lack of maintenance, is the function of this library complete? I am considering whether to try it.

**Comment by hhhhh322** [comment]
@reisenmiao @ETO-QSH Actually, this project isn't useful except as an example. It can't use the newest Spine files - it only supports the old format. Even if you follow the pull request instructions, you won't be able to run it directly since you'd need to fix numerous bugs. Additionally, it's built on PyGame, so if you want to integrate it with PyQt/PySide, you might need to use QT's official libraries and potentially tools like CFFI (I'm not certain). Speaking from experience, I ended up using JPype and libGDX in my project to get Spine working, as I haven't found any functional Spine implementations elsewhere.

**Comment by ETO-QSH** [comment]
@hhhhh322 

I actually used PYQT to draw Windows and handle events, so I wanted to follow the QT stack (especially its traversal feature), and I found that libGDX and QT both support OpenGL rendering, which means I can render with spine's libgdx-API and play with QT, so I might try that direction.

CFFI direction I also tried, but there is no free time to do it. I don't think there will be a spine-python implementation for a long time in the future, the official said that there is no time to develop and maintain, based on libGDX is probably the best integration I have found.

Thank you for your help.
